### ISSUE TITLE
no bower.json nor readme

### ISSUE THREAD

**Issue by Morriz** [matthewyarlett/AngularJS-Directive-for-SharePoint-People-Picker#3]
Hi, first of all, thanks for wanting to share what you made.

But could you please not dump code like this, without a readme?

Also, I am under the assumption that your scripts folder contains 3rd party code that can easily be found in bower and npm, so why not use one of those package managers? Nobody cuts and pasts scripts anymore...

Maybe you work in Micros0ft world, where it's totally ok to be ignorant of best practices and open source philosophies...but correct me if I'm wrong

**Comment by matthewyarlett** [comment]
Thanks Morriz. 

I've added a Readme file. 

I see your point about the third party scripts, but in this instance, I'd rather people be able to easily download the solution (example) as a whole.
